export default {
    '系统管理': 'System Management',
    '栏目管理': 'Column Management',
    '角色管理': 'Role Management',
    '权限管理': 'Permission Management',
    '用户管理': 'User Management',
    product_management: 'Product Management',
    category_management: 'Category Management',
    fittings_management: 'Fittings Management',
    fittings_stock: 'Fittings Stock Management',
    commodity_management: 'Commodity Management',
    pdt_series_management: 'Tag Management',
    site_management: 'Site Management',
    pdt_template_management: 'Template Management',
    pdt_template_process: 'Selection List',
    pdt_template_factory: 'Template List',
    pdt_template_studio: 'Rendering List',
    pdt_template_studio_price: 'Rendering Cost',
    pdt_template_factory_price: 'Template Cost',
    produce: 'Production Management',
    produce_factory_list: 'Factory List',
    produce_factory_produce: 'Production List',
    produce_factory_produce_record: 'Production Records',
    produce_purchase: 'Purchase List',

    '统计': 'Statistics',
    '登出': 'Sign out',

    '点击上传': 'Click to upload',
    '上传限制': 'Limited to {ext} files，up to {size}',
    '权限': 'Permission',
    'processing': 'Processing',

    order: {
        distribution: {
            confirm: {
                over: 'Please confirm：SKU（{sku}），Size（{size}），Quantity（{total}）',
            }
        },
        delivery: {
            total: 'There are{total}orders waiting for delivery',
        },
        status: {
            pending: 'Pending',
            cancelled: 'Cancelled',
            waiting_shipped: 'Wait for shipment',
            shipped: 'Shipped',
            pick_waiting: 'To be assorted',
            picking: 'Assorting',
            pick_completed: 'Complete assortment',
            pending_purchase: 'To be purchased',
            purchase: 'Being purchased',
            purchase_completed: 'Purchase completed',
            processing: 'Processing',
            complete: 'Complete',
            distributing: 'Distributing',
            distribute_waiting: 'To be distributed',
            distribute_completed: 'Distribution completed',
            distribute_return: 'Return',
            waiting_accept: 'To be inspected for quality acceptance',
            waiting_repair: 'Waiting for repair',
            being_repaired: 'Start repairing',
            waiting_production: 'To be produced',
            in_production: 'In production',
            product_passed: 'Quality inspection passed',
            rework: 'Reworking',
            in_stock: 'In stock',
            return_process: 'Returning for refund',
            return_process_part: 'Returning for refund(partial)',
            return_completed: 'Returned',
            return_part_completed: 'Returned(partial)',
            exchange_process: 'Exchanging',
            exchange_process_part: 'Exchanging(partial)',
            exchange_completed: 'Exchanged',
            exchange_part_completed: 'Exchanged(partial)',
            waiting_transfer: 'Ready for transhipment',
            transferring: 'In transit',
            transferred: 'Transhipped',

            normal: 'Normal order',
            address_changed: 'Update shipping address',
            item_changed: 'Change SKU',
            shipping_method_changed: 'Change shipping method',
            change_confirmed: 'Change confirmed',
            paused: 'Order suspended',
        },
        history: {

            100: 'Original order details',
            101: 'Payment status updates to paid',
            102: 'Warehouse preemption',
            103: 'Obtain tracking number',
            104: 'Distributed for production/purchase',
            105: 'Create new order at back-end',


            200: 'Change SPU',
            201: 'Change size',
            202: 'Change the quantity of the products',
            203: 'Cancel part of the products',
            204: 'Change engraving',
            205: 'Update shipping address',
            206: 'Change the quantity of the order',
            207: 'Change the image of the order',
            210: 'Cancel pending',
            211: 'Put order in priority',
            212: 'Cancel order',
            213: 'Update  shipping address',
            214: 'Modify payment status',
            215: 'Order status updates to ready for shipment',
            216: 'Change shipping method',
            217: 'Update tracking number',
            218: 'Order status updates to shipped',
            230: 'Modify refund amount',
            231: 'Refund application approved',
            232: 'Refund application rejected',
            233: 'Refunded',
            234: 'Refund failed',


            222: 'Note',
            223: 'Notes of Customer Service',


            302: 'Add product',
            303: 'Apply for refund',
            304: 'Apply for return for refund',
            305: 'Apply for return for exchange',
            306: 'Apply for reshipment',
            307: 'Apply for return',
            308: 'Return completed',


            403: 'Refund approved',
            404: 'Return for refund approved',
            405: 'Return for exchange approved',
            406: 'Reshipment approved',
            407: 'Order priority approved',
            408: 'Review order',


            1001: 'Abnormal',
            1002: 'Philippines problem',
            1003: 'Return&Exchange',
            1004: 'Issue parcel',
            1005: 'Reason for Refund',
            1006: 'Contact customer',
            1007: 'Cause for defects',
            1008: 'Customer Issue',
            1009: 'Put order on hold',
            1010: 'Return for refund',
            1011: 'Reship',


            501: 'Storage + Reservation',
            502: 'Put back in storage after order cancellation',
            503: 'Priority confirmed',
            504: 'Change confirmed',
            506: 'Request for quality acceptance',
            507: 'Start processing',
            508: 'Complete assortment',
            509: '加入转运包',
            510: '移除转运包',
        },
        issue: {
            1: 'General category',
            2: 'Product category',
            3: 'Ring',
            4: 'Necklace',
            5: 'Bracelet',
            6: 'Magento category',
            7: 'US site',
            25: 'Earring',
            70: 'Customer problem',
            71: 'Pre-sales',
            72: 'Mid-sales',
            73: 'After-sales',
            74: 'Quality issue',
            75: 'Stone fell out',
            76: 'Color fading',
            79: 'Size issue',
            80: 'Personal preference',
            81: 'Jewelry information',
            82: 'Payment method',
            85: 'Track order status',
            86: 'Distorted',
            90: 'Shipping method',
            91: 'Return policy&warranty',
            94: 'Change information of a paid order',
            95: 'Customs fee related issue',
            96: 'Cause for defects',
            97: 'Stone fell out',
            98: 'Need re-plating',
            99: 'Wrong engraving',
            100: 'Blurry engraving',
            101: 'Engraving for stock item',
            102: 'Remove engraving for purchased item',
            103: 'Wrong item',
            104: 'Miss the side band',
            105: 'Stone quality issue',
            106: 'Wrong size',
            108: 'Colour aberration',
            109: 'Contact customer',
            110: 'Physical Address Needed for expedited/express shipping',
            111: 'Phone number to be confirmed',
            112: 'City and Zip code do not match',
            113: 'Customer opened dispute',
            114: 'Out of Stock',
            115: 'Reason for refund',
            116: 'Whole order cancelled',
            117: 'Return for refund',
            118: 'Discount',
            119: 'Refund for partial cancellation',
            120: 'Compensation for customs fee',
            121: 'Refund for undelivered/missing parcel',
            122: 'Price difference',
            123: 'Incorrect stone color',
            124: 'Incorrect quantity',
            125: 'To confirm if mutiple same items were ordered',
            128: 'Customs Clearance Issue',
            130: 'City and Country do not match',
            132: 'Duplicate order',
            133: 'Shipping address is ambiguous',
            134: 'City and State do not match',
            135: 'Address in English is needed for DHL shipping',
            136: 'Order change needs to be confirmed',
            137: 'Unsuccessful delivery',
            138: 'UPS/DHL Express cannot deliver to military addresses',
            139: 'CPF number needed for Brazil customer',
            140: 'Not for individual sale',
            141: 'Large order to be confirmed',
            143: 'Italy site',
            154: 'Chile site',
            155: 'Order issue',
            156: 'Logistics has not been updated for more than 30 days',
            157: 'Empty parcel/ partial missing item',
            158: 'Parcel unreceived while tracking shows delivered',
            159: 'Return for refund',
            160: 'Return for size exchange',
            161: 'Return for design exchange',
            162: 'Stone fell out',
            163: 'Color fading',
            164: 'The object does not match the picture',
            165: 'Encountered tariffs',
            166: 'Expedited/Express shipping changes to free shipping',
            167: 'Engraving isn\'t satisfying',
            168: 'Engraving content needs confirming',
            169: 'Quality isn\'t satisfying',
            170: 'Not as expected',
            172: 'Cloudy (Not Shining)Stone',
            173: 'Adjustable ring',
            174: 'Distorted',
            175: 'Wrong item sent',
            176: 'Uncomfortable wearing',
            177: 'Reason for exchange',
            178: 'For exchanging size',
            179: 'Size gap = 1/4',
            180: 'Size gap = 1',
            181: 'For exchanging design',
            182: 'The object does not match the picture',
            183: 'Cloudy (Not Shining)Stone',
            184: 'Not as expected',
            185: 'Size doesn\'t fit',
            186: 'Stone fell out',
            187: 'Cheap looking',
            188: 'Engraving isn\'t satisfying',
            189: 'Colour aberration',
            191: 'Quality isn\'t satisfying',
            192: 'Cut finger',
            193: 'Hooking or clipping hair',
            194: 'Pieces don\'t stay together',
            195: 'Wrong item',
            202: 'For repairing',
            203: 'Stone fell out',
            204: 'Color fading',
            205: 'Distorted',
            206: 'Cloudy (Not Shining)Stone',
            207: 'Other reason (please specify)',
            208: 'Other reason (please specify)',
            216: 'Other reason (please specify)）',
            217: 'Reason for return',
            218: 'The object does not match the picture',
            219: 'Cloudy (Not Shining)Stone',
            220: 'Not as expected',
            221: 'Size doesn\'t fit',
            222: 'Stone fell out',
            223: 'Cheap looking',
            224: 'Engraving isn\'t satisfying',
            225: 'Colour aberration',
            226: 'Quality isn\'t satisfying',
            227: 'Cut finger',
            228: 'Hooking or clipping hair',
            229: 'Pieces don\'t stay together',
            230: 'Refused parcel',
            231: 'Logistics hasn\'t updated for a long time',
            232: 'Parcel returned due to abnormal logistics',
            233: 'Other reason (please specify)',
            234: 'Remove the special engraving',
            242: 'Reason for reshipment',
            243: 'Lost parcel',
            244: 'Empty parcel',
            245: 'Missing item',
            246: 'Parcel unreceived while tracking shows delivered',
            247: 'Parcel returned due to abnormal logistics ',
            248: 'Other reason (please specify)',
            249: 'Reason for return/exchange/reshipment',
            250: 'Size gap ≥2',
            251: 'Size gap = 1/2',
            252: 'Size gap = 3/4',
            273: 'Custom necklace',
            274: 'Custom bracelet',
            275: 'Custom ring',
            276: '2≥Size gap ≥1',
            277: 'Free shipping doesn\'t support this country,DHL fee is needed',
            278: 'Stone is too big',
            279: 'Stone is too big',
            280: 'Not as expected',
            281: 'Not as expected',
            283: 'Philippines feeback for abnormality',
            284: 'Lost parcel',
            286: 'Empty parcel',
            288: 'Missing item',
            289: 'Parcel unreceived while tracking shows delivered',
            290: 'Parcel returned due to abnormal logistics',
            292: 'Payment Issue',
            293: 'Other reason (please specify)',
            295: 'Philippines General Inquiry',
            297: 'Just For Record',
            298: 'To follow up',
            300: 'Packing',
            301: 'Blurred photo',
            303: 'Color fading',
            304: 'On hold reason',
            305: 'Product on hold',
            306: 'Address on hold',
            307: 'Logistics are not configured for the country',
            308: 'Tracking number cannot be generated',
            309: 'Return to the new',
        },
        type: {
            custom: 'Customized item',
            taobao: 'Outsourced item',
            stock: 'Stock item',
            mixture: 'Mixed order',
            fictitious: 'Virtual item',
            suit: 'Set',
            null: '-',
            package:'package',
        },
        payment: {
            processing: 'Processing',
            canceled: 'Canceled',
            closed: 'Closed',
            complete: 'Complete',
            fraud: 'Suspected Fraud',
            holded: 'On hold',
            payment_review: 'Payment_review',
            paypal_canceled_reversal: 'Paypal_canceled_reversal',
            paypal_reversed: 'Paypal_reversed',
            pending: 'Pending',
            pending_payment: 'Pending_payment',
            pending_paypal: 'Pending_paypal'
        },
        refund_status: {
            0: 'To be processed',
            1: 'Processing',
            2: 'Refund Application Approved',
            3: 'Refunded',
            4: 'Refund Application Rejected',
            5: 'Follow up Ongoing',
            6: 'Refund Failed',
            7: 'Solved',
        },
        return: {
            type: {
                0: 'Return for refund',
                1: 'Return for exchange',
            },
            status: {
                0: 'In transit',
                1: 'Arranged',
                2: 'Arranged(customer service)',
            },
        },
        issue_status:{
            'pending':'To be contacted',
            'solved':'Solved',
            'processing':'Pending',
        },
    },
    //common
    common: {
        add: 'Add',
        view: 'View',
        edit: 'Edit',
        delete: 'Delete',
        ok: 'Ok',
        save: 'Save',
        cancel: 'Cancel',
        operate: 'Operate',
        please_select: 'Please select',
        prompt: 'Prompt',
        none_select: 'You did not select any entries',
        confirm_delete: 'This action will permanently delete the entry, continue?',
        picture: 'Picture',
        id: 'ID',
        yes: 'Yes',
        no: 'No',
        amount: 'Quantity',
    },
    product: {
        category: {
            name: 'Name',
            key: 'Key',
            status: 'If usable',
        },
        stock: {
            factory: 'Production plant',
            storehouse: 'Warehouse',
            size: 'Size'
        },
        user_set: {
            color: 'Plating color',
            engraving: 'Engraving',
            letters: 'Letter',
            stone: 'Stone',
            font: 'Font',
            fontSize: 'Font size',
            sku: 'SKU',
            amount: 'Quantity',
            G1: 'Stone 1',
            G2: 'Stone 2',
            G3: 'Stone 3',
            G4: 'Stone 4',
            M1: 'Material 1',
            M2: 'Material 2',
            M3: 'Material 3',
            M4: 'Material 4',
            R1: 'Ring 1',
            R2: 'Ring 2',
            R3: 'Ring 3',
            R4: 'Ring 4',
            1: 'Group 1',
            2: 'Group 2',
            3: 'Group 3',
            4: 'Group 4',
            5: 'Group 5',
            6: 'Group 6',
            7: 'Group 7',
            8: 'Group 8',
            9: 'Group 9',
            man: 'Man',
            woman: 'Woman',
            customEngravings: 'Engraving',
            phrase: 'Message',
            constellation: 'Constellation',
            symbol: 'Letter',
        },
        detail: {
            engrave_label: 'Engraving content', phrase: 'Phrase', engrave_font: 'Engraving font', target_area: 'Target area'
        },
        product: {
            base: 'Base',
            category_name: 'Category',
            name: 'Name',
            spu: 'SPU',
            osku: 'OSKU',
            supply_stock: 'Re-stocking',
            url_key: 'Url Key',
            template_no: 'Article No',
            selling_price: 'Selling price',
            market_price: 'Market price',
            special_price: 'Special price',
            special_price_date: 'Special price range',
            is_clearance: 'Clearance Situation',
            is_customize: 'If for customization',
            is_set: 'If it\'s set',
            spu_set: 'Set SPU',
            pics: 'Product picture',
            short_description: 'Brief description',
            description: 'Description',
            brand: 'Brand',
            engrave_max_len: 'Maximum number of engraving characters',
            plating_color: 'Plating color',
            series: 'Style',
            style: 'Style',
            size_list: 'Size list',
            size_type: 'Size type',
            template_id: 'Template ID',
            template_attr: 'Template attribute',
            template_group_num: 'Template group number',
            group_fee: 'Template group fee',
            man_size: 'Man size',
            women_size: 'Woman size',
            facebook_pid: 'Facebook Association ID',
            designer: 'Designer',
            copyright: 'Copyright',
            support_stock: 'Stock Support',
            ringCustomShow: 'Ring custom option',
            necklaceCustomShow: 'Necklace custom option',
            simple_ring_type: 'Single-piece ring',
            relation: 'Related products',
            zip: 'Zip',
            show3d: '3D display',
            materials: 'Material',
            material: 'Material',
            add_material: 'Add material',
            delete_material: 'Delete material',
            reset_price: 'Reset price',
            engraving: 'Engraving',
            add_engraving: 'Add engraving',
            delete_engraving: 'Delete engraving',
            add_ring: 'Add ring',
            delete_ring: 'Delete ring',
            inner_engraving: 'Engraving（inner）',
            outer_engraving: 'Engraving（outer）',
            stone: 'Stone',
            add_stone: 'Add stone',
            delete_stone: 'Delete stone',
            color: 'Color',
            auto_rule: 'Auto rule',
            real_image: 'Real image',
            price: 'Price',
            none: 'None',
            normal: 'Normal',
            created_at: 'Create time',

        },
        validate: {
            choose: 'Please choose{name}',
            input: 'Please input{name}',
            max_input: 'Add up to{num}',
        }
    }

};