export default {
    "仓库": "Warehouse",
    '/system/user.add': 'System management-user management-add user',
    '/stock/storehouseList.add': 'Warehouse management-create warehouse',
    '/product/add': 'Product management-add product',
    '/product/delete': 'Product management-delete product',

    "data.commodity.site.jeulia_site": "Commodity management-site management-jeulia",
    "data.commodity.site.gnoce_site": "Commodity management-site management-gnoce",
    "data.commodity.site.jeulia_online_site": "Commodity management-site management-jeulia-test environment",
    "/product/update": "Product management-update product",
    "data.produce.produce_list.xian": "Factory management-production management-xian factory",
    "data.produce.produce_list.shengzhen": "Factory management-production management-shenzhen factory",
    "data.produce.produce_list.guangzhou": "Factory management-production management-guangdong factory",
    "data.produce.produce_list.xingfuhao": "Factory management-production management-xingfuhao factory",
    '/order/list/approved.operation': 'Order management-order review-review permission',
    '/order/refund/apply.operation': 'Order management-refund review-review permission',
    '/order/refund/apply.refund_status5':'订单管理-退款审核-跟进中',
    '/order/refund/apply.refund_status7':'订单管理-退款审核-跟进完成',
    '/order/list.change.pay.status': 'Order management-modify payment status',
    '/product/template.price.edit_multi': 'Template management-factory cost price record(multi)',
    '/product/template.price.edit_once': 'Template management-factory cost price record(once)',
    '/produce/factory_produce.accept': 'Production management-production list-quality acceptance',

    "请扫码或输入订单号": "Please scan code or enter the order number",
    "订单编号": "Reference number",
    "加急": "Priority",
    "订单号": "Order number",
    "类型": "Classification",
    "创建时间": "Order date",
    "订单状态": "Order status",
    "跟踪状态": "Order change state",
    "备注": "Note",
    "备注添加": "Add note",
    "备注查看": "Click for details",
    "操作": "Operate",
    "Site": "Site",
    "Language": "Language",
    "编辑": "Edit",
    "取 消": "Cancel",
    "确 定": "Confirm",
    "详细信息": "Detailed information",
    "保 存": "Save",
    "关 闭": "Close",
    "部门管理": "Department management",
    "类别管理": "Category management",
    "邮件模板": "Email template",
    "订单管理": "Order management",
    "订单列表": "Order list",
    "订单审核": "Order-confirm list",
    "联系客户": "Contact customer",
    "配货管理": "Assortment management",
    "打印面单-发货": "Print shipping label-ship",
    "创建订单": "Create order",
    "退款审核": "Refund center",
    "退款管理": "Refund management",
    "退换货物流管理": "Return & Exchange Center",
    "耗材管理": "Supplies management",
    "仓库管理": "Warehouse management",
    "仓库物流配置": "Warehouse logistics configuration",
    "国家地区管理": "Country abbreviation management",
    "库存管理": "Inventory management",
    "补库存管理": "Re-stocking management",
    "库存预占管理": "Stock reservation managment",
    "库存日志": "Inventory log",
    "进销存管理": "In-out-stock management",
    "进销存库存": "Purchase-sell-stock",
    "进销存日志": "Purchase-sell-stock log",
    "海外仓管理": "Overseas warehouse management",
    "转运打包": "Transhipment packing",
    "转运拆包": "Transhipment unpacking",
    "退货单号管理": "Return management",
    "异常件问题": "Mark abnormal",
    "打印面单": "Print shipping label",
    "已发货": "Shipped",
    "物流信息": "Logistics information",
    "发货时间": "Shipping date",
    "未发货": "Unship",
    "物流": "Shipping method",
    "物流单号": "Tracking number",
    "修改": "Modify",
    "添加子部门": "Add sub-department",
    "负责人": "Person in charge",
    "人员": "Personnel",
    "删除部门": "Delete department",
    "请添写名称": "Please add title",
    "名称": "Title",
    "新增 权限": "Add permission",
    "描述": "Description",
    "请添写权限路径": "Please add permissable URL ",
    "请添写描述": "Please add description",
    "权限路径": "Permissable URL",
    "权限描述": "Permission description",
    "新建员工": "Add personnel",
    "部门": "Department",
    "删除": "Delete",
    "用户名": "Username",
    "昵称": "Nickname",
    "密码": "Password",
    "请添写用户名": "Please add username",
    "请添写密码": "Please add password",
    "/*": "/*",
    "/order/refund": "/order/refund",
    "/order/refund/marger": "/order/refund/marger",
    "/shipment/": "/shipment/",
    "/shipment/embzip": "/shipment/embzip",
    "/shipment/index": "/shipment/index",
    "/shipment/return/shipment": "/shipment/return/shipment",
    "/template": "/template",
    "确认要删除吗？": "Please confirm the [delete]",
    "添加子分类": "Add sub-category",
    "删除分类": "Delete category",
    "站点": "Site",
    "模板类型": "Template type",
    "模板名称": "Template name",
    "状态": "Status",
    "邮件标题": "Email subject",
    "模板说明": "Template description",
    "关闭": "Close",
    "线上Jeulia": "Online Jeulia",
    "Gnoce官网": "Gnoce official website",
    "预览": "Preview",
    "禁用": "Diable",
    "新订单通知邮件": "Confirmation email for new order",
    "订单第一次发货": "First shipment",
    "sku变更": "Change sku",
    "刻字变更": "Change engraving",
    "尺码变更": "Change size",
    "数量变更": "Change the quantity ordered",
    "添加产品": "Add product",
    "取消部分产品": "Cancel part of the products",
    "取消整个订单": "Cancel the whole order",
    "修改物流方式": "Change shipping method",
    "修改收货地址（包含收货人名字、电话等）": "Update shipping address（including receipient name,contact number, and so on）",
    "申请重发": "Apply for reshipment",
    "退货换货": "Return for exchange",
    "换货完成": "Exchanged",
    "退货退款": "Return for refund",
    "退款完成": "Returned and refunded",
    "第二次发货": "Second shipment",
    "启用": "Enable",
    "请输入内容后回车": "Please input content and then press ENTER",
    "图片": "Image",
    "支付状态": "Payment status",
    "产品状态": "Product status",
    "待定": "On hold state",
    "订单金额": "Order amount",
    "优惠券": "Coupon code",
    "支付方式": "Payment method",
    "订单追踪状态": "Order change state",
    "订单物流方式": "Shipping method",
    "订单物流编号": "Logistics reference number",
    "刻字内容": "Engraving content",
    "街道": "Address",
    "城市": "City",
    "国家简码": "Country abbreviation",
    "查看": "View order",
    "申请退款": "Apply for refund",
    "退回": "Return",
    "重发": "Reship",
    "发票": "Download invoice",
    "取消订单": "Cancel order",
    "地址": "Address",
    "取消待定": "Cancel pending",
    "已支付": "Paid",
    "canceled": "Canceled",
    "closed": "Closed",
    "已完成": "Completed",
    "fraud": "Suspected Fraud",
    "holded": "On hold",
    "payment_review": "Payment_review",
    "paypal_canceled_reversal": "Paypal_canceled_reversal",
    "paypal_reversed": "Paypal_reversed",
    "未支付": "Unpaid",
    "pending_payment": "Pending_payment",
    "pending_paypal": "Pending_paypal",
    "包装": "Packing",
    "订单信息": "Order information",
    "order.type.undefined": "Order.type.undefined",
    "order.status.undefined": "Order.status.undefined",
    "支付信息": "Payment information",
    "订单总金额": "Product amount",
    "order.payment.undefined": "Order.payment.undefined",
    "支付金额": "Paid amount",
    "运费": "Shipping fee",
    "积分抵扣": "Points deduction",
    "礼品卡": "Gift card",
    "已退金额": "Refund amount",
    "客户信息": "Customer information",
    "尺码": "Size",
    "数量": "Quantity",
    "价格": "Price",
    "刻字": "Engraving",
    "添加商品": "Add product",
    "编辑信息": "Edit information",
    "SPU": "SPU",
    "单价": "Unit price",
    "收货地址": "Shipping address",
    "历史记录": "Order update history",
    "发货记录": "Shipment history",
    "客服备注": "Remark history",
    "添加客服备注": "Add remark",
    "DHL": "DHL",
    "UPS": "UPS",
    "EUB": "EUB",
    "FEDEX": "FEDEX",
    "ARAMEX": "ARAMEX",
    "EMB": "EMB",
    "客户姓名": "Ship to Name",
    "客户邮箱": "Customer's Email Address",
    "是否注册": "If registered",
    "姓名": "Receipient Name",
    "电话": "Contact Number",
    "邮箱": "Email",
    "国家": "Country",
    "省市": "State/City",
    "邮编": "Zip code",
    "修改收货地址": "Update shipping address",
    "查看修改地址链接": "View link for address modification",
    "发送修改地址邮件": "Send email for address modification",
    "备注信息": "Note details",
    "退款金额": "Refund amount",
    "退 货": "Return for refund",
    "换 货": "Return for exchange",
    "物流公司": "Shipping courier",
    "创建人": "Operator",
    "审核通过": "Approved",
    "产品": "Product",
    "问题类型": "Order issue",
    "创建者": "Operator",
    "处理者": "Handler",
    "问题状态": "Issue Status",
    "处理状态": "Processing Status",
    "查看订单": "View Order",
    "处理中": "Processing",
    "已解决": "Solved",
    "导出库存配货单": "Export stock order",
    "请扫码或输入生产编号": "Please scan the code or enter the production number",
    "生产编号": "Production number",
    "申请人": "Applicant",
    "退款状态": "Refund status",
    "处理人": "Handler",
    "退款tag": "Reason for the refund",
    "退回物流": "Shipping carrier",
    "退回类型": "Reason for return",
    "退回状态": "Return status",
    "匹配结果": "Matching result",
    "退回物流单号": "Tracking number for return",
    "顶级分类": "Top classification",
    "add": "Add",
    "导出": "Export",
    "添加配件": "Add fittings",
    "编号": "Reference number",
    "形状": "Shape",
    "请选择": "Please select",
    "颜色": "Color",
    "色系": "Color scheme",
    "材质": "Material",
    "品牌": "Brand",
    "规格(mm)": "Specification(mm)",
    "形状系": "Shape scheme",
    "切割": "Cut",
    "重量(g)": "Weight(g)",
    "克拉(ct)": "Karat(ct)",
    "添加标签": "Add tag",
    "key": "Key",
    "新建耗材": "Add supplies",
    "采购": "Purchase",
    "更新标签": "Update label",
    "请输入key": "Please enter key",
    "保存": "Save",
    "取消": "Cancel",
    "获取类目": "Obtain category",
    "同步商品排序": "Synchronize product sorting",
    "标题": "Title",
    "产品SPU": "Product SPU",
    "产品名称": "Product name",
    "排序": "Sorting",
    "请选择站点": "Please select site",
    "同步至Mangeto": "Synchronize to Mangeto",
    "类目": "Category",
    "magentoID": "MagentoID",
    "同步时间": "Sync Time",
    "选择类目": "Select category",
    "同步": "Sync",
    "未同步": "Unsynchronized",
    "添加站点": "Add site",
    "版本": "Version",
    "邮件配置": "Email configuration",
    "属性": "Attribute",
    "复制版图": "Copy template",
    "版号": "Article No.",
    "产品类型": "Item Type",
    "存在属性": "Existing attributes",
    "成本价": "Cost price",
    "例如：>10": "For example：>10",
    "开版编号": "Template serial number",
    "选品编号": "Selection number",
    "版型分类": "Pattern classification",
    "是否原创": "If original",
    "电镀颜色": "Plating color",
    "选品人": "Selector",
    "工厂名称": "Factory Name",
    "开版": "Mold making",
    "开版完成": "Molding completed",
    "工厂验收": "Factory acceptance",
    "流程完成": "Complete flow",
    "否": "No",
    "复制": "Copy",
    "请输入选品编号": "Please enter selection number",
    "请选择版型": "Please select pattern",
    "请填写成本价": "Please input cost price",
    "请填写版号": "Please input pattern number",
    "请填写采购地址": "Please input purchasing address",
    "请选择分类": "Please select category",
    "请选择工厂": "Please select factory",
    "请选择渲染团队": "Please select rendering team",
    "版型类别": "Pattern type",
    "开版工厂": "Molding Factory",
    "采购地址": "Purchasing address",
    "分类": "Classification",
    "参考图": "Reference image",
    "是否开版": "If molding",
    "开版价格": "Molding Cost",
    "是否渲染/拍图": "If rendering/photograph",
    "渲染团队": "Rendering team",
    "渲染价格": "Rendering price",
    "选品理由": "Reason for the selection",
    "开版说明": "Molding description",
    "录入模板属性": "Enter the template attributes",
    "请输入版号": "Please enter the Article No.",
    "请输入成本价": "Please enter the cost price",
    "请选择材质": "Please select material",
    "请输入重量": "Please enter weight",
    "重量": "Weight",
    "克": "Gram",
    "宽度": "Width",
    "毫米": "Millimeter",
    "高度": "Height",
    "厚度": "Thickness",
    "宝石": "Gem",
    "选择宝石": "Select gem",
    "完成选择": "Complete the selection",
    "规格": "Specification",
    "克拉": "Karat",
    "内径": "Inner diameter",
    "添加选品": "Add selection",
    "确认发起": "Confirm",
    "流程结束": "Complete flow",
    "类别": "Category",
    "步骤": "Procedure",
    "流程": "Flow",
    "更新选品": "Update selection",
    "示意图": "Abridged general view",
    "开始渲染": "Start rendering",
    "渲染完成": "Rendering completed",
    "是": "Yes",
    "请输入价格": "Please enter price",
    "请选择类型": "Please select type",
    "支付": "Pay",
    "结束时间": "End Time",
    "渲染类型": "Rendering Type",
    "录入价格": "Input Price",
    "添加工厂": "Add Factory",
    "权重": "Importance",
    "更新工厂": "Update Factory",
    "请输入名称": "Please enter name",
    "概率": "Probability",
    "确认删除该条目吗": "Please confirm the [delete]",
    "请输入数量": "Please enter quantity",
    "批量打印": "Batch printing",
    "生产批次": "Production batch",
    "serial_id": "Serial_id",
    "ext_order_id": "Ext_order_id",
    "sku": "Sku",
    "SKU": "SKU",
    "生产数量": "Production quantity",
    "请求验收数量": "Requested Quantity for acceptance check",
    "已验收数量": "Quality Accepted quantity",
    "是否刻字": "If engraved",
    "变更确认": "Change confirmed",
    "下单时间": "Order Date",
    "开始时间": "Start Time",
    "请求验收": "Request for quality acceptance",
    "生产总数": "Total production",
    "验收通过": "Quality Acceptance Passed",
    "验收数量": "Quantity for acceptance check",
    "详情": "Details",
    "开始生产": "Start production",
    "打印标签": "Print Label",
    "已确认": "Confirmed",
    "待确认": "To be confirmed",
    "确认变更": "Changed confirmed",
    "验收": "Quality Acceptance",
    "生产状态": "Production Status",
    "生产工厂": "Production plant",
    "OutKey": "OutKey",
    "参数": "Parameter",
    "效果图": "Effect Picture",
    "生产时间": "Production time",
    "工厂": "Factory",
    "交货时间": "Delivery Time",
    "库存": "Inventory",
    "编辑库存": "Edit inventory",
    "批次": "Batch",
    "采购数量": "Purchase quantity",
    "更新时间": "Update time",
    "实际采购数量": "Actual purchase quantity",
    "开始采购": "Start purchasing",
    "外采地址": "Supplier Site",
    "添加仓库": "Add warehouse",
    "仓库名称": "Warehouse Name",
    "联系人": "Contact",
    "仓库所在国家": "Warehouse located country",
    "仓库地址": "Warehouse Address",
    "更新": "Update",
    "请输入仓库名称": "Please enter the name of the warehouse",
    "请输入联系人": "Please enter the contact",
    "请输入仓库所在国家": "Please enter the warehouse located country",
    "请输入仓库地址": "Please enter the warehouse address",
    "新增": "Add",
    "覆盖地区": "Coverage area",
    "物流类型": "Logistics type",
    "物流方式": "Shipping method",
    "英国仓": "UK warehouse",
    "美国仓": "US warehouse",
    "广州仓": "Guangzhou warehouse",
    "普通": "Regular",
    "标准": "Standard",
    "快捷": "Express",
    "CN": "CN",
    "UK": "UK",
    "ZA": "ZA",
    "US": "US",
    "CA": "CA",
    "请选择仓库": "Please select the warehouse",
    "请选择仓库覆盖地区": "Please select the warehouse's coverage area",
    "请选择物流类型": "Please select the type of logistics",
    "请选择物流方式": "Please select the shipping method",
    "请输入概率": "Please enter the probability",
    "添加": "Add",
    "国家地区简称": "Country abbreviation",
    "查看配置": "View configuration",
    "请输入国家地区简称": "Please enter the country abbreviation",
    "Size": "Size",
    "现有库存数量": "Existing stock quantity",
    "起": "From",
    "止": "To",
    "在补库存数量": "Re-stocking Amount",
    "预占库存数量": "Reserve stock quantity",
    "补库存": "Re-stocking",
    "弃件": "Discard",
    "弃件取消": "Cancel the discard",
    "库存预占详细": "Details of the pre-occupied Inventory",
    "日志": "Log",
    "请输入补库存数量": "Please enter the amount of stock up",
    "补库存数量": "The amount of stock up",
    "广州厂": "Guangzhou Plant",
    "确定": "Confirm",
    "预占数量": "Pre-occupied amount",
    "预占时间": "Pre-occupied time",
    "预占取消时间": "Reservation cancelled time",
    "预占中": "Being occupied",
    "预占取消": "Reservation cancelled",
    "操作人": "Operator",
    "当时库存数量": "Former stock amount",
    "当时在补数量": "Former re-stocking amount",
    "当时预占数量": "Former pre-occupied amount",
    "操作时间": "Operating time",
    "发起补库存": "Initiate restocking",
    "补库存入库": "Replenish inventory",
    "订单补库存入库": "Initiate restocking for existing order",
    "订单取消入库": "Put cancelled order into stock",
    "库存预占": "Stock pre-occupied",
    "库存预占取消": "Cancel the pre-occupied stock",
    "库存预占取消部分": "Cancel part of the pre-occupied stock",
    "发货": "Shipped",
    "验收通过数量": "Accepted amount after inspection",
    "现有库存成本": "Current inventory cost",
    "累计入库数量": "Cumulative storage volume",
    "累计入库成本": "Cumulative storage cost",
    "累计销售数量": "Accumulated sales volume",
    "累计销售成本": "Cumulative cost of sales",
    "累计弃件数量": "Accumulated discard amount",
    "累计弃件取消数量": "Accumulated discard cancellation amount",
    "当时库存成本": "Former inventory cost",
    "当时累计入库数量": "Former cumulative storage volume",
    "当时累计入库成本": "Former cumulative storage cost",
    "当时累计销售数量": "Former accumulated sales volume",
    "当时累计销售成本": "Former cumulative cost of sales",
    "当时累计弃件数量": "Former accumulated discard amount",
    "当时累计弃件取消数量": "Former accumulated discard cancellation amount",
    "入库": "Input",
    "出库": "Output",
    "请选择线路": "Please select the route",
    "新建大包裹": "Create parcel",
    "线路": "Route",
    "包裹名称": "Parcel Name",
    "扫码": "Scan code",
    "修改包裹": "Update the parcel",
    "扫码打包": "Assemble orders",
    "扫码录入": "Scan code",
    "发送物流": "Ship parcel",
    "录入运单号": "Enter the tracking number",
    "扫码解包": "Scan code",
    "扫码 打面单 发货": "Scan code  Print shipping label  Ship",
    "扫码录入物流编号": "Scan code to enter the logistics reference number",
    "物流编号": "Logistics reference number",
    "匹配数量": "Matching quantity",
    "退回 IDS": "Return tracking number",
    "UPS成人签收": "UPS adult signature",

    "任务监控": "Task monitoring",
    "物流管理": "Logistics management",
    "EUB物流管理": "EUB Logistics",
    "待审核": "Pending Review",
    "取消商品": "Cancel",
    "16 cm = 6.3 in ": "16 cm = 6.3 in ",
    "17 cm = 6.7 in ": "17 cm = 6.7 in ",
    "18 cm = 7.1 in ": "18 cm = 7.1 in ",
    "19 cm = 7.5 in ": "19 cm = 7.5 in ",
    "20 cm = 7.9 in ": "20 cm = 7.9 in ",
    "21 cm = 8.3 in ": "21 cm = 8.3 in ",
    "22 cm = 8.7 in ": "22 cm = 8.7 in ",
    "地区": "State",
    "国家代码（两个字符：如US）": "Country code",
    "确认要取消订单吗": "Please confirm the 【Cancel order】",
    "已没有可以操作的商品": "There is no product that can be operated",
    "确认删除吗?": "Please confirm the 【Delete】",
    "OLD SKU 搜索": "OLD SKU Search",
    "打印条码": "Print bar code",
    "贴码+完成配货": "Attach sticker + Complete assortment",
    "完成配货": "Complete assortment",
    "即将打印订单号并完成配货？": "Ready to print order number and complete assortment?",
    "OLD SKU 搜索": "OLD SKU Search",
    "打印条码": "Print bar code",
    "贴码+完成配货": "Attach sticker + Complete assortment",
    "完成配货": "Complete assortment",
    "即将打印订单号并完成配货？": "Ready to print order number and complete assortment?",
    "导出EUB订单": "Export EUB order",
    "导入物流文件": "Import logistics file",
    "下载物流模板": "Download Logistics Template",
    "扫码后自动打印面单并发货": "Automatically print shipping label and ship order after scanning",
    "手动处理": "Manual processing",
    "创建原因": "Reason for creation",
    "收货信息": "Delivery information",
    "产品信息": "Product information",
    "物流时效": "Logistics timeliness",
    "普通时效": "Normal timeliness",
    "标准时效": "Standard timeliness",
    "快速时效": "Express timeliness",
    "EUB订单已处理完毕": "EUB Order processed",
    "Priority": "Priority",
    "Order date": "Order date",
    "Order change state": "Order change state",
    "Classification": "Classification",
    "Remark details": "Remark details",
    "Items SKU": "SKU",
    "Items Status": "Product status",
    "Items Type": "Classification",
    "请设置打印机": "Please set up the printer",
	"退回完成": "Returned",
	"邮件日志": "Email log",
    "item_defective_status_0": "Pending",
    "item_defective_status_1": "In hand",
    "item_defective_status_2": "Processed",
    "确认要审核通过此订单？": "Please confirm the 【Approval】?",
    "修改订单信息可能会发生仓库变更，确认修改吗": "Order information update may occur warehouse changes, please confirm the 【Modification】?",
    "成本": "Cost",
    "修正库存": "Modify inventory",
    "次品管理": "Defective product management",
    "/order/defective": "Defective product management",
    "/order/list/delivery": "/order/list/delivery",
    "/order/list/distribution.stock.GuangZhou": "Order-Assortment management-GuangZhou",
    "/order/list/distribution.stock.LosAngeles": "Order-Assortment management-LosAngeles",
    "/shipment/importShipmentNo": "/shipment/importShipmentNo",
    "/template/email_log": "Email template-Email logs",
    "操作失败，不能重复申请": "The operation failed and the application could not be repeated",
    "是否清仓": "Clearance situation",
    "/stock/index/restock": "库存管理-库存管理-补库存",
    "/stock/index/drop": "库存管理-库存管理-弃件",
    "/stock/index/drop_cancel": "库存管理-库存管理-弃件取消",
    "/stock/index/adjustment": "库存管理-库存管理-修正库存",
    "/stock/storehouseList/edit": "仓库管理-仓库管理-更新",
    "/stock/storehouseAreaRel/update": "仓库管理-仓库物流配置-更新",
    "/stock/storehouseAreaRel/deleteData": "仓库管理-仓库物流配置-删除",
    "/stock/areaList/update": "仓库管理-国家地区管理-更新",
    "/stock/areaList/deleteData": "仓库管理-国家地区管理-删除",
    "产品编号":"Product reference number",
    "订单变更确认邮件":"Send confirmation email for order modification",
    "发送订单修改确认邮件":"Send confirmation email for order modification",
    "/order/list.seePrice":"Order management-View the amount",
    "/order/list.remark":"Order management-Service-Remark",
    "/order/list.updateOrder":"Order management-Modify",
    "/order/list.updateOrder.address":"Order management-Modify-Modify Address",
    "/shipment/doImportShipmentNo": "物流管理-EUB物流管理-导入物流",
    "/order/list.updateOrder.shipment": "订单管理-订单列表-查看订单-修改订单物流",
    "/order/list.exportUpsEds": "订单管理-订单列表-导出UPS电子报关单",
    "/order/list.exportUpsTpl": "订单管理-订单列表-导出UPS模板",
    "/order/list.exportDhlTpl": "订单管理-订单列表-导出DHL模板",
    "/order/list.exportFedexTpl": "订单管理-订单列表-导出FEDEX模板",
    "/order/list.exportAramexTpl": "订单管理-订单列表-导出ARAMEX模板",
    "/order/list.exportEubTpl": "订单管理-订单列表-导出EUB模板",
    "申请时间": "Application date",
    "审核日期": "Date of approval",
    "退款日期": "Refund date",
    "审核人": "Verifier",
    "退款人": "Refund operator",
    "/order/list.fields.ext_order_id":"订单管理-订单列表-查看订单编号",
};