export default {
    '系统管理': '系统管理',
    '栏目管理':'栏目管理',
    '角色管理':'角色管理',
    '权限管理':'权限管理',
    '用户管理':'用户管理',
    product_management : '产品管理',
    category_management : '分类管理',
    fittings_management : '配件管理',
    fittings_stock : '配件库存管理',
    commodity_management : '商品管理',
    pdt_series_management : '标签管理',
    site_management : '站点管理',
    pdt_template_management : '版图管理',
    pdt_template_process : '选品列表',
    pdt_template_factory : '开版列表',
    pdt_template_studio : '渲染列表',
    pdt_template_studio_price : '渲染费用',
    pdt_template_factory_price : '开版费用',
    produce : '生产管理',
    produce_factory_list : '工厂列表',
    produce_factory_produce : '生产列表',
    produce_factory_produce_record : '生产记录',
    produce_factory_produce_report : '生产报告',
    produce_purchase : '采购列表',

    '统计': '统计',
    '登出':'登出',

    '点击上传':'点击上传',
    '上传限制':'只能上传{ext}文件，且不超过{size}',
    '权限':'权限',
    'processing':'处理中',
    
    order:{
        distribution:{
            confirm:{
                over:'请核对信息：SKU（{sku}），尺寸（{size}），数量（{total}）',
            }
        },
        delivery:{
            total:'还有 {total} 个订单等待发货',
        },
        status:{
            pending:'等待处理',
            cancelled:'已取消',
            waiting_shipped:'等待发货',
            shipped:'已经发货',
            pick_waiting:'等待配货',
            picking:'配货中',
            pick_completed:'配货完成',
            pending_purchase:'等待采购',
            purchase:'采购中',
            purchase_completed:'采购完成',
            processing:'备货中',
            complete:'交易完成',
            distributing:'分发中',
            distribute_waiting:'等待分发',
            distribute_completed:'分发完成',
            distribute_return:'全部返回',
            waiting_accept:'等待验收',
            waiting_repair:'等待返修',
            being_repaired:'开始返修',
            waiting_production:'等待生产',
            in_production:'生产中',
            product_passed:'验货通过',
            rework:'返修中',
            in_stock:'已入库',
            return_process:'退货中',
            return_process_part:'退货中(部分)',
            return_completed:'已退回',
            return_part_completed:'已退回(部分)',
            exchange_process:'换货中',
            exchange_process_part:'换货中(部分)',
            exchange_completed:'换货完成',
            exchange_part_completed:'换货完成(部分)',
            waiting_transfer:'待转运',
            transferring:'转运中',
            transferred:'转运完毕',

            normal:'正常订单',
            address_changed:'修改地址',
            item_changed:'修改产品',
            shipping_method_changed:'修改物流公司',
            change_confirmed:'确认修改',
            paused:'订单暂停',
        },
        history:{

            100:'商城原始订单',
            101:'订单变为已支付',
            102:'进行仓库预占',
            103:'获取运单号码',
            104:'分发工厂生产/采购',
            105:'后台新建订单',


            200:'修改SPU',
            201:'修改产品尺码',
            202:'修改产品数量',
            203:'取消产品',
            204:'修改产品刻字',
            205:'修改收货地址',
            206:'修改订单数量',
            207:'修改订单图片',
            210:'取消待定订单',
            211:'加急订单',
            212:'取消订单',
            213:'网页端修改收货地址',
            214:'修改支付状态',
            215:'订单改为待发货',
            216:'修改订单物流',
            217:'修改订单物流号码',
            218:'订单改为已发货',
            230:'修改退款金额',
            231:'退款审核通过',
            232:'退款审核失败',
            233:'退款成功',
            234:'退款失败',


            222:'备注',
            223:'客服备注',


            302:'添加产品',
            303:'申请退款订单',
            304:'申请退货订单',
            305:'申请换货订单',
            306:'申请重发订单',
            307:'申请退回',
            308:'退回完成',




            403:'同意退款订单',
            404:'同意退货订单',
            405:'同意换货订单',
            406:'同意重发订单',
            407:'同意加急订单',
            408:'审核订单',


            1001:'异常件',
            1002:'菲律宾问题',
            1003:'退换货',
            1004:'问题件',
            1005:'退款原因',
            1006:'联系客户',
            1007:'次品原因',
            1008:'客服问题',
            1009:'待定订单',
            1010:'退回退款',
            1011:'重发',


            501:'入库+预占',
            502:'取消订单后入库',
            503:'确认加急',
            504:'确认变更',
            506:'请求验收',
            507:'开始处理',
            508:'完成配货',
            509:'加入转运包',
            510:'移除转运包',
        },
        issue:{
                1:'总类目',
            2:'产品分类',
                3:'戒指',
            4:'项链',
                5:'手链',
            6:'Magento 类目',
                7:'美国站',
            25:'耳环',
                70:'客服问题',
            71:'售前',
                72:'售中',
            73:'售后',
                74:'质量问题',
            75:'掉石',
                76:'掉色',
            79:'尺码问题',
                80:'款式（个人喜好）问题',
            81:'询问产品',
                82:'询问付款方式',
            85:'查单物流问题',
                86:'变形',
            90:'询问物流方式',
                91:'询问退货及产品保障政策',
            94:'修改订单问题',
                95:'关税问题',
            96:'次品原因',
                97:'掉石',
            98:'需要返电',
                99:'字印错',
            100:'字印模糊',
                101:'库存刻字',
            102:'淘宝去刻字',
                103:'错款',
            104:'少副戒',
                105:'石头质量问题',
            106:'尺寸错',
                108:'色差问题',
            109:'联系客户',
                110:'P.O.BOX地址',
            111:'电话号码问题',
                112:'城市与邮编不符',
            113:'客户提出争议',
                114:'产品断货',
            115:'退款原因',
                116:'取消订单退款',
            117:'退货退款',
                118:'折扣退款',
            119:'改数量退款',
                120:'关税补贴退款',
            121:'包裹未妥投退款',
                122:'差价退款',
            123:'石头颜色不对',
                124:'数量不对',
            125:'核实客户购买多件同款产品',
                128:'遇到清关问题',
            130:'城市与国家不符',
                132:'重复订单',
            133:'地址不详细',
                134:'城市和州不符',
            135:'非英文地址打不了DHL',
                136:'订单修改内容需核实',
            137:'包裹派送未成功',
                138:'军事地址',
            139:'巴西客户需联系提供CPF number',
                140:'非单卖品',
            141:'订单购买产品较多，需核实',
                143:'意大利站',
                154:'智利站',
            155:'订单问题',
                156:'物流超过30天未更新',
            157:'客诉收到空包或者产品部分缺失',
                158:'物流显示签收，客诉未收到',
            159:'退回退款',
                160:'退回换尺码',
            161:'退回换款式',
                162:'掉石',
            163:'掉色',
                164:'实物与图片差异',
            165:'遇到关税',
                166:'加急改免邮运费退款',
            167:'对刻字不满意',
                168:'刻字内容需核实',
            169:'对质量不满意',
                170:'不喜欢款式',
            172:'钻不够闪亮',
                173:'活口戒指',
            174:'产品变形',
                175:'物流后端发错货',
            176:'戴着不舒服',
                177:'退回换货原因',
            178:'退回换尺码',
                179:'尺码差距刚好1/4',
            180:'尺码差距刚好1寸',
                181:'退回换款式',
            182:'实物与图片不符',
                183:'石头不亮',
            184:'款式不合适（不喜欢）',
                185:'尺码不合适',
            186:'掉钻',
                187:'看起来廉价',
            188:'刻字不满意',
                189:'有色差',
            191:'质量不满意',
                192:'割手/磨手',
            193:'夹头发',
                194:'闭合不够严密',
            195:'错件退回换',
                202:'退回修理',
            203:'掉钻',
                204:'掉色',
            205:'变形',
                206:'钻不亮',
            207:'其他原因（客服自行备注）',
                208:'其他原因（客服自行备注）',
            216:'其他原因（客服自行备注）',
                217:'退回退款原因',
            218:'实物与图片不符',
                219:'石头不亮',
            220:'款式不喜欢（不合适）',
                221:'尺码不合适',
            222:'掉钻',
                223:'看起来廉价',
            224:'刻字不满意',
                225:'有色差',
            226:'质量不满意',
                227:'割手/磨手',
            228:'夹头发',
                229:'闭合不够严密',
            230:'拒收退回',
                231:'物流长时间不更新',
            232:'物流直接退回',
                233:'其他原因（客服自行备注）',
            234:'去特殊字印',
            242:'重发原因',
                243:'丢件',
            244:'空包裹',
                245:'缺件',
            246:'显示妥投未收到',
                247:'物流退回',
            248:'其他原因（客服自行备注）',
                249:'退款、换货、重发原因',
            250:'尺码差距2寸以上（包含2寸）',
                251:'尺码差距刚好1/2',
            252:'尺码差距刚好3/4',
                273:'定制款项链',
            274:'定制款手链',
                275:'定制款戒指',
            276:'尺码差距超过1寸且小于2寸',
                277:'国家发不了免邮eub，需付DHL运费',
            278:'石头太大',
                279:'石头太大',
            280:'不是预期的',
            281:'不是预期的',
                283:'菲律宾异常件问题',
            284:'丢件',
                286:'空包裹',
            288:'缺件',
                289:'显示妥投未收到',
            290:'物流退回',
                292:'付款问题',
            293:'其他原因（客服自行备注）',
            295:'菲律宾问题分类',
                297:'仅登记作用',
            298:'需要跟进',
            300:'包装',
                301:'照片模糊',
                303:'掉色',
            304:'待定原因',
                305:'产品待定',
            306:'地址待定',
            307:'客户国家没有配置物流',
            308:'无法生成物流单号',
            309:'退回换新',
        },
        type:{
            custom:'工厂款',
            taobao:'外采款',
            stock:'库存款',
            mixture:'混合单',
            fictitious:'虚拟',
            suit:'套装包',
            null:'-',
            package:'包装',
        },
        payment:{
            processing:'Processing',
            canceled:'Canceled',
            closed:'Closed',
            complete:'Complete',
            fraud:'Suspected Fraud',
            holded:'On hold',
            payment_review:'Payment Review',
            paypal_canceled_reversal:'Paypal Canceled Reversal',
            paypal_reversed:'Paypal Reversed',
            pending:'Pending',
            pending_payment:'Pending Payment',
            pending_paypal:'Pending Paypal'
        },
        refund_status:{
            0:'待处理',
            1:'处理中',
            2:'审核通过',
            3:'已退款',
            4:'审核不通过',
            5:'跟进中',
            6:'退款失败',
            7:'跟进完成',
        },
        return:{
            type:{
                0:'退回退钱',
                1:'退回换货',
            },
            status:{
                0:'等待退回',
                1:'自动完成',
                2:'客服完成',
            },
        },
        issue_status:{
            'pending':'未解决',
            'solved':'问题解决',
            'processing':'解决中',
        },
    },
    //common
    common : {
        add : '添加',
        view : '查看',
        edit : '编辑',
        delete : '删除',
        ok : '确 定',
        save : '保 存',
        cancel : '取 消',
        operate : '操作',
        please_select : '请选择',
        prompt : '提示',
        none_select : '您没有选择任何条目',
        confirm_delete : '此操作将永久删除该条目, 是否继续?',
        picture : '图片',
        id : 'ID',
        yes : '是',
        no : '否',
        amount : '数量',
    },
    product :{
        category : {
            name : '名称',
            key : '标识',
            status : '是否可用',
        },
        stock:{
            factory:'生产工厂',
            storehouse:'仓库',
            size:'尺寸'
        },
        user_set:{
          color:'电镀颜色', engraving:'刻字',letters:'字母',stone:'石头',font:'字体',fontSize:'字号',sku:'SKU',amount:'数量',
            G1:'宝石一',G2:'宝石二',G3:'宝石三',G4:'宝石四',M1:'指环一材质',M2:'指环二材质',M3:'指环三材质',M4:'指环四材质',
            R1:'指环一',R2:'指环二',R3:'指环三',R4:'指环四',1:'组1',2:'组2',3:'组3',4:'组4',5:'组5',6:'组6',7:'组7',8:'组8',9:'组9',
            man:'男',woman:'女',customEngravings:'刻字',phrase:'寄语',constellation:'星座',symbol:'字母',
            garnet:'1月-石榴红', amethyst:'2月-紫色', aquamarine:'3月-海蓝', crystal:'4月-白色', emerald:'5月-祖母绿', light_amethyst:'6月-浅紫', ruby:'7月-大红色', peridot:'8月-橄榄绿', sapphire:'9月-宝蓝色', rose_quartz:'10月-玫瑰色', topaz:'11月-黄晶色', blue_zircon:'12月-蓝色',
            'Name' :  '名字',    '1st Name' :  '第一个名字',    '2nd Name' :  '第二个名字',    '3rd Name' :  '第三个名字',    '4th Name' :  '第四个名字',    '5th Name' :  '第五个名字',    '6th Name' :  '第六个名字',    '7th Name' :  '第七个名字',    'Birthstone' :  '生辰石',    '1st Birthstone' :  '第一个石头',    '2nd Birthstone' :  '第二个石头',    '3rd Birthstone' :  '第三个石头',    '4th Birthstone' :  '第四个石头',    '5th Birthstone' :  '第五个石头',    '6th Birthstone' :  '第六个石头',    '7th Birthstone' :  '第七个石头',    'Father Name' :  '父亲的名字',    'Mother Name' :  '母亲的名字',    'Initial(Only one letter)' :  '首字母',    '1st Inscription' :  '第一个刻字',    '2nd Inscription' :  '第二个刻字',    '3rd Inscription' :  '第三个刻字',    'Personalized Phrase' :  '刻字',    'Phrase' :  '刻字',    '1st Name(Capital please)' :  '第一个名字',    '2nd Name(Capital please)' :  '第二个名字',    'Name on Heart' :  '心形上的文字',    'Chain Length(for the heart)' :  '心形项链长度',    'Name on The Key' :  '钥匙上的文字',    'Chain Length(for the key)' :  '钥匙项链长度',    'Name on the left bar' :  '左边的名字',    'Name on the right bar' :  '右边的名字',    'Left Letter' :  '左边的字母',    'Milddle Letter' :  '中间的字母',    'Right Letter' :  '右边的字母',    'Middle Name' :  '中间的名字',    'Middle Birthstone' :  '中间的石头',    'Left Name' :  '左边的名字',    'Right Name' :  '右边的名字',    'Left Birthstone' :  '左边的石头',    'Right Birthstone' :  '右边的石头',    'Name on Big Disc' :  '大圆环上的名字',    'Name on Middle Disc' :  '中圆环上的名字',    'Name on Small Disc' :  '小圆环上的名字',    'Inscription' :  '刻字',    'Left Inscription' :  '左面刻字',    'Right Inscription' :  '右面刻字',    'Back Inscription' :  '后面刻字',    'Front Inscription' :  '前面刻字',    'Inscription(Name,word or date)' :  '刻字',    'Left Letter(low case)' :  '左边的字母',    'Middle Letter(capital)' :  '中间的字母',    'Right Letter(Low case)' :  '右边的字母',    'Enter up to 3 initials(In the order you want them to appear)' :  '字母',    'Enter up to 3 initials (In the order you want them to appear)' :  '字母',    'Month' :  '月份',    'Date' :  '日期',    'Year' :  '年份',    'Latitude & Longitude Coordinates' :  '坐标',    'Chain Length' :  '链子长度',    'Color' :  '电镀颜色',    'Bar Inscription' :  '条形牌刻字',    'Heart inscription' :  '心形刻字',    'Circle inscription(Names should be separated by commas)' :  '圆环刻字',    'Initial' :  '字母',    '1st Chain Length' :  '第一条链子长度',    '2nd Chain Length' :  '第二条链子长度',    '1st Color' :  '第一个颜色',    '2nd Color' :  '第二个颜色',    'Chain Length(for the tag)' :  '标牌项链的长度',    'Name on Tag' :  '标牌上的名字',    '1st Letter' :  '第一个字母',    '2nd Letter' :  '第二个字母',    '3rd Letter' :  '第三个字母',    '4th Letter' :  '第四个字母',    'Left heart name':'左边心形上的名字',    'Select left chain length':'选择左边项链长度',    'Right heart name':'右边心形上的名字',    'Select right chain length':'选择右边项链长度',    'Name on Tiny Disc':'极小圆环上的名字',
    'Name on Medium Disc':'中圆环上的名字',
    'Side Inscription':'侧面刻字',    'Name on Boy Chram':'男孩刻字',    'Name on Girl Charm':'女孩刻字',    'Select Constellation':'选择星座',    'Address':'地址',    'Upper birthstone':'上面的生辰石',    'Lower birthstone':'下面的生辰石',    'Inner heart inscription':'内侧心上的刻字',    'Outer heart inscription':'外侧心上的刻字',    'Small heart inscription':'小号心形上的刻字',    'Medium heart inscription':'中号心形上的刻字',    'Large heart inscription':'大号心形上的刻字',    'Small heart birthstone':'小号心形上的生辰石',    'Medium heart birthstone':'中号心形上的生辰石',    'Large heart birthstone':'大号心形上的生辰石',    'Charm engraving':'charm上的刻字',    'Please add your disc engraving (Names should be separated by commas)':'圆盘上的刻字',    'Left Baby Feet Inscription':'左边脚丫上的刻字',    'Right Baby Feet Inscription':'右边脚丫上的刻字',    'Inside engraving':'内侧刻字',    'Aries':'白羊座',    'Taurus':'金牛座',    'Gemini':'双子座',    'Cancer':'巨蟹座',    'Leo':'狮子座',    'Virgo':'处女座',    'Libra':'天秤座',    'Scorpio':'天蝎座',    'Sagittarius':'射手座',    'Capricorn':'摩羯座',    'Aquarius':'水瓶座',    'Pisces':'双鱼座',    'First Initial':'第一个字母',    'Second Initial':'第二个字母',    'Please select the first child chain length':'第一条子链的长度',    'Please select the second child chain length':'第二条子链的长度',    'Please select the mother chain length':'母链的长度',        },
        detail:{
            engrave_label:'刻字名称',phrase:'短语',engrave_font:'刻字字体',target_area:'图片标识位',none:'通用',women:'女款',men:'男款'
        },
        product:{
            base : '基本',
            category_name : '类别',
            name : '名称',
            spu : 'SPU',
            osku : 'OSKU',
            supply_stock : '补库存',
            url_key : 'Url Key',
            template_no : '版号',
            selling_price : '售价',
            market_price : '市场价',
            special_price : '优惠价',
            special_price_date : '优惠价范围',
            is_clearance : '是否清仓',
            is_customize : '是否定制',
            is_set : '是否套装',
            spu_set : '套装SPU',
            pics : '产品图',
            short_description : '简短描述',
            description : '描述',
            brand : '品牌',
            engrave_max_len : '最大刻字数',
            plating_color : '电镀颜色',
            series : 'Style',
            style : '款式',
            size_list : '尺寸列表',
            size_type : '尺寸类型',
            template_id : '模板ID',
            template_attr : '模板属性',
            template_group_num : '模板group数量',
            group_fee : '模板group费用',
            man_size : '男尺寸',
            women_size : '女尺寸',
            facebook_pid : 'Facebook关联ID',
            gtin : 'Gtin',
            designer : '设计师',
            copyright : '版权',
            support_stock : '支持库存',
            ringCustomShow : '戒指定制选项',
            necklaceCustomShow : '项链定制选项',
            simple_ring_type : '单戒类型',
            relation:'关联产品',
            zip : '压缩包',
            show3d : '3D展示',
            materials : '素材',
            material : '材质',
            add_material : '添加材质',
            delete_material : '删除材质',
            reset_price : '重填价格',
            engraving : '刻字',
            add_engraving : '添加刻字',
            delete_engraving : '删除刻字',
            add_ring : '添加指环',
            delete_ring : '删除指环',
            inner_engraving : '刻字（内）',
            outer_engraving : '刻字（外）',
            stone : '宝石',
            add_stone : '添加宝石',
            delete_stone : '删除宝石',
            color : '颜色',
            auto_rule : '自动规则',
            real_image : '实拍图',
            price : '价格',
            none : '无',
            normal : '普通',
            created_at : '创建时间',
            edit_series : '标签设置',

        },
        template:{
            template_type:'版图类型',
            factory:'工厂'
        },
        validate:{
            choose : '请选择{name}',
            input : '请输入{name}',
            max_input : '最多添加{num}个',
        }
    },
    email_template:{
        log:{
            id:'ID',
            send_mail:'发件人',
            send_name:'名称',
            reply_to:'发件人',
            site_id:'站点',
            mailto:'收件人',
            template_type:'类型',
            template_data:'数据',
            email_title:'邮件标题',
            email_content:'邮件内容',
        }
    }
};